### PR TITLE
Godep workspace -> vendor

### PR DESCRIPTION
**Pull request by dav**

### CODE REVIEW

**Comment by kevinburke** [comment]
Gah, I think you're going to run into some problems here. First, I believe `git.go` still tries to import `"github.com/Shyp/go-git/Godeps/_workspace/src/github.com/github/hub/commands"`, which isn't correct anymore, the import path should just be "github.com/github/hub/commands".

Second (and this is 100% my fault, I didn't know better) since this is a library, and not a binary, it really shouldn't ship with a vendor folder at all - whatever is importing this should have a vendor directory, and can choose whatever versions of dependencies it wants. 

You can un-rewrite the Godeps imports by running:

```
godep save -r=false ./...
```

Then I'd just remove the vendor directory entirely if I were you. 

Sorry for leaving this in such a miserable state.

**Comment by dav** [comment]
@kevinburke yeah, this has been a pain so far! Thanks for update, will look into your suggestion.

Trying to update `cli` and everything of ours it depends on for Go 1.7.3 and the new vendor dependency format....

**Comment by kevinburke** [comment]
yep. if this is still a pain hop in the #vendor channel on Gophers slack: https://invite.slack.golangbridge.org/

**Comment by caseycrites** [comment]
🍧

**Pull request merged**
